spring:
  application:
    name: yandex-kafka
  kafka:
    bootstrap-servers: kafka-0:7093, kafka-1:7095, kafka-2:7097
    ssl:
      trust-store-location: file:/opt/yandex-kafka/kafka-0-creds/kafka.truststore.jks
      trust-store-password: kafka-pass
      key-store-location: file:/opt/yandex-kafka/kafka-0-creds/kafka.keystore.jks
      key-store-password: kafka-pass
      key-password: kafka-pass
    properties:
      security.protocol: SASL_SSL
      sasl.mechanism: PLAIN
      sasl.jaas.config: org.apache.kafka.common.security.plain.PlainLoginModule required username="admin" password="admin-secret";
      schema.registry.url: http://schema-registry:8081
      schema.registry.ssl.truststore.location: /opt/yandex-kafka/kafka-0-creds/kafka.truststore.jks
      schema.registry.ssl.truststore.password: kafka-pass
      schema.registry.ssl.keystore.location: /opt/yandex-kafka/kafka-0-creds/kafka.keystore.jks
      schema.registry.ssl.keystore.password: kafka-pass
      schema.registry.ssl.key.password: kafka-pass
    consumer:
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.ErrorHandlingDeserializer
      group-id: filtered-product
      properties:
        specific.avro.reader: true
        spring.json.trusted.packages: "ru.yandex.practicum.model.*"
        spring.json.value.default.type: "ru.yandex.practicum.model.avro.Product"
        spring.deserializer.value.delegate.class: io.confluent.kafka.serializers.KafkaAvroDeserializer
    producer:
      acks: all
      retries: 3
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: io.confluent.kafka.serializers.KafkaAvroSerializer
    streams:
      application-id: practicum-kafka-streams-app
      properties:
        default.key.serde: org.apache.kafka.common.serialization.Serdes$StringSerde
        default.value.serde: io.confluent.kafka.streams.serdes.avro.SpecificAvroSerde
        schema.registry.url: http://schema-registry:8081
        schema.registry.ssl.truststore.location: /opt/yandex-kafka/kafka-0-creds/kafka.truststore.jks
        schema.registry.ssl.truststore.password: kafka-pass
        schema.registry.ssl.keystore.location: /opt/yandex-kafka/kafka-0-creds/kafka.keystore.jks
        schema.registry.ssl.keystore.password: kafka-pass
        schema.registry.ssl.key.password: kafka-pass

topic:
  products:
    name: products-topic
    partitions: 3
    replicas: 2
    min-insync-replicas: 2
  filtered-products:
    name: filtered-products-topic
    partitions: 3
    replicas: 2
    min-insync-replicas: 2

