spring:
  datasource:
    url: jdbc:postgresql://postgres:5432/postgres
    username: postgres
    password: pass
    driver-class-name: org.postgresql.Driver
  jpa:
    properties.hibernate:
      batch_size: 50
      fetch_size: 50
      show_sql: true
      format_sql: true
      hbm2ddl.auto: update
  application:
    name: yandex-kafka
  kafka:
    bootstrap-servers: kafka-0:9094, kafka-1:9095, kafka-2:9096
    consumer:
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.ErrorHandlingDeserializer
      group-id: kafka-connect-message
      properties:
        spring.json.trusted.packages: "ru.yandex.practicum.dto.*"
        spring.deserializer.value.delegate.class: org.springframework.kafka.support.serializer.JsonDeserializer

topic:
  users:
    name: yandex.public.users
    partitions: 3
    replicas: 2
    min-insync-replicas: 2
#  orders:
#    name: filtered-messages-topic
#    partitions: 3
#    replicas: 2
#    min-insync-replicas: 2

