route:
  repeat_interval: 5m
  group_interval: 5m
  receiver: 'telegram'
receivers:
  - name: 'telegram'
    telegram_configs:
      - api_url: 'https://api.telegram.org'
        bot_token: '8165963945:AAH_Gr10zsiMkYyDlbaKoF62rQyudXqzIEA'
        chat_id: 392963520
        parse_mode: ''   # добавьте это, чтобы отключить разметку




