clusters = cluster-1, cluster-2
cluster-1.bootstrap.servers = kafka-0:7093,kafka-1:7095,kafka-2:7095
cluster-2.bootstrap.servers = kafka-1-0:9093,kafka-1-1:9095,kafka-1-2:9095

bootstrap.servers = kafka-0:7093,kafka-1:7095,kafka-2:7095
security.protocol=SASL_SSL
sasl.mechanism=PLAIN
ssl.truststore.location=/etc/kafka/secrets/kafka.truststore.jks
ssl.truststore.password=kafka-pass
ssl.truststore.type=JKS
ssl.endpoint.identification.algorithm=https

cluster-1.security.protocol=SASL_SSL
cluster-1.sasl.mechanism=PLAIN
cluster-1.ssl.truststore.location=/etc/kafka/secrets/kafka.truststore.jks
cluster-1.ssl.truststore.password=kafka-pass
cluster-1.ssl.truststore.type=JKS
cluster-1.ssl.endpoint.identification.algorithm=https

cluster-2.security.protocol=SASL_SSL
cluster-2.sasl.mechanism=PLAIN
cluster-2.ssl.truststore.location=/etc/kafka/secrets/kafka-1.truststore.jks
cluster-2.ssl.truststore.password=kafka-pass
cluster-2.ssl.truststore.type=JKS
cluster-2.ssl.endpoint.identification.algorithm=https

cluster-1->cluster-2.enabled = true
cluster-1->cluster-2.topics = filtered_products
cluster-1->cluster-2.emit.heartbeats.enabled = true
cluster-1->cluster-2.emit.checkpoints.enabled = true
cluster-1->cluster-2.tasks.max = 2
replication.policy.class = org.apache.kafka.connect.mirror.IdentityReplicationPolicy

replication.factor = 3
checkpoints.topic.replication.factor = 3
heartbeats.topic.replication.factor = 3
offset.syncs.topic.replication.factor = 3

config.storage.topic = connect-config-storage
offset.storage.topic  = connect-offset-storage
status.storage.topic  = connect-status-storage
config.storage.replication.factor = 3
offset.storage.replication.factor = 3
status.storage.replication.factor = 3

value.converter.schemas.enable=true
internal.key.converter.schemas.enable=false
internal.value.converter.schemas.enable=true