Client {
 org.apache.kafka.common.security.plain.PlainLoginModule required
 username="kafka1"
 password="kafka-secret";
};

KafkaServer {
 org.apache.kafka.common.security.plain.PlainLoginModule required
 username="admin"
 password="admin-secret"
 user_admin="admin-secret"
 user_kafka-ui="admin-secret";
};