Client {
 org.apache.kafka.common.security.plain.PlainLoginModule required
 username="kafka1"
 password="kafka-secret"
 user_kafka1="kafka-secret";
};

KafkaClient {
    org.apache.kafka.common.security.plain.PlainLoginModule required
    username="admin"
    password="admin-secret";
};

KafkaServer {
 org.apache.kafka.common.security.plain.PlainLoginModule required
 username="admin"
 password="admin-secret"
 user_admin="admin-secret"
 user_kafka-ui="admin-secret"
 user_client1="admin-secret";
};